# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yaa Otchere
email: yaa@yaaotchere.ca
description: > # this means to ignore newlines until "baseurl:"
  I am a front end devloper and a youth worker carving out my own unique space in the tech industry.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yaaotchere.github.io/blog" # the base hostname & protocol for your site
twitter_username: yaatotchere
github_username:  yaaotchere

# Build settings
markdown: kramdown
